services:
    application_mongo_database.mongo:
        class: MongoClient

    application_mongo_database.db:
        class: MongoDB
        factory_service: application_mongo_database.mongo
        factory_method: selectDB
        arguments: ["test_db"]

    application_mongo_database.manager:
        class: Application\Mongo\DatabaseBundle\Service\Manager