services:
    application_ukrlogic_akkordtourbundle.akkordgateway:
        class: Application\UkrLogic\AkkordTourBundle\Service\BusTours
        arguments:
            - @guzzle.akkord_tour_bus
            - @application_ukr_logic_akkord_tour.country_repository
            - @application_ukr_logic_tourbundle.tour_repository
            - @doctrine.orm.entity_manager
        tags:
            -  { name: 'application_ukrlogic_tourbundle.service.gateway', alias: 'akkord_tour_bus' }