services:
    application_ukrlogic_akkordtourbundle.service.tourparser:
        class: Application\UkrLogic\AkkordTourBundle\Service\TourParser
        arguments:
            - @guzzle.akkord_tour_bus
            - @application_ukrlogic_tourbundle.country_repository
            - @application_ukr_logic_tourbundle.tour_repository
            - @doctrine.orm.entity_manager

    application_ukrlogic_akkordtourbundle.service.tourrepository:
        class: Application\UkrLogic\AkkordTourBundle\Service\TourRepository
        arguments: [ @application_ukr_logic_tourbundle.tour_repository ]
        tags:
            - { name: 'tour_repository', alias: 'bus' }