services:
    application_ukrlogic_tourclientbundle.service.tourrepository:
        class: Application\UkrLogic\TourClientBundle\Service\TourRepository
        arguments:
            - @session
            - @guzzle.tour_client_avia
            - @application_ukrlogic_tourbundle.hotel_repository
        tags:
            - { name: 'tour_repository', alias: 'avia' }
